### ISSUE TITLE
Alternative 2D Libraries?

### ISSUE THREAD

**Issue by svengeance** [sungaila/PDFtoImage#103]
Hey! This library looks amazing, so thank you first off for the hard work.

I was wondering if you'd considered componentizing the rendering pipeline such that we could install separate packages for different providers? For instance, `PDFToImage.Skia` and `PDFToImage.ImageMagick` and `PDFToImage.ImageSharp`. 

I'm selfishly asking out of curiosity for my own use-case, where I already have ImageMagick installed, and it would be cool to be able to reuse it. In this same project I was delighted to find Zxing implemented something similar: https://www.nuget.org/packages/ZXing.Net.Bindings.Magick/

Thanks for the consideration!

**Comment by sungaila** [comment]
Hi @svengeance,

that's a good idea! This library has switched from GDI to SkiaSharp before so a weaker coupling would be desirable.

However, there are a few reasons I don't want to implement multiple 2D graphic backends right now:
- `PDFtoImage` should be the only NuGet package to reference. I want to avoid a situation where you have to pick and choose packages (when you don't know or don't care).
- The public APIs includes `SKBitmap` right now. Depending on how this library is split, it might be a breaking change.
- [Internally the rendering is dependant on `SKBitmap` and `SKCanvas` right now.](https://github.com/sungaila/PDFtoImage/blob/0e589c8407e9e4c585e0eaae9d73aa01c1442b13/src/PDFtoImage/Internals/PdfDocument.cs#L182C17-L230C18) Might be a hassle to decouple this since it is used to stitch multiple bitmaps together.

A compromise might be to split this library into `PDFtoImage` and `PDFtoImage.Core`. The latter package contains interfaces for the rendering stuff. The former package has adapters for SkiaSharp and the current API as is.

I'll take a look at this. You will have to write your own ImageMagick adapter, however, when this package is split in two.

Greetings
David

**Comment by svengeance** [comment]
Fair game of course on implementing our own bindings. I wasn't expecting it to be nonbreaking and a fair amount of work on your end. 

Personally I think it might benefit you in the long run as well, as swapping providers might provide some measurable performance or reliability gains in the future, in addition to the consumer benefits of being able to reuse existing image libraries.

Thank you for considering it!

**Comment by sungaila** [comment]
So I gave it a try and attempted to abstract the render logic from the underlying 2d graphics library. It quickly became a overcomplicated mess.

- I split the package into `PDFtoImage.Core` and `PDFtoImage.Adapters.SkiaSharp`. This broke the existing API because depening on which adapter you have chosen, the public API surface changed drastically.
- On my first attempt I used reflection to load the current adapter. But this doesn't work properly when using trimming/ahead-of-time compilation (unless you put tons of attributes into the code telling the compiler what is trimmable and what is not).
- Then I tried calling the render logic inside the adapters. But now this class library has hundred lines of code when the original plan was just to abstract `SKBitmap` and `SKCanvas`.
- And then I thought about using dependency injection but that would bloat the library even further.

Right now I can't find a solution for "the adapter library should contain nothing but the bitmap and canvas implementations"and "the library must be fully AoT compatible" at the same time.

Maybe I'll try again at a later date, but I'll give up for now.

**Comment by svengeance** [comment]
I appreciate it! On the offchance I get some time, would it be appreciated if I put together my own rendition and pinged you here to see if it's a tenable solution, or would you rather not deal with the overhead at all? No worries either way, just trying to balance being helpful and annoying 😅

**Comment by sungaila** [comment]
Feel free to fork and give it a try yourself! :)
